# Analise de todos fundos imobiliarios

### link: https://www.kaggle.com/datasets/jaumdezeeni/todos-os-fundos-de-investimento-imobilirio-da-b3

#### campos do arquivo a ser analisado
-- Nome, Razão Social,  Codigo,  Setor, Segmento,

## Algumas perguntas
- Quantidade de segmentos diferentes
- Quantos tipos de segmentos disponiveis
- Quantos setores diferentes
- Quantidade de fundos por segmento
- Quais tickers estão em cada segmento

In [4]:
import os

In [20]:
BASE_DIR = os.path.dirname(os.path.abspath('.'))
DATA_DIR = os.path.join(BASE_DIR, 'data')

## carregando as libs

In [32]:
import pandas as pd
from pandasql import sqldf

## carregando arquivos

In [21]:
df = pd.read_csv(os.path.join(DATA_DIR, "todos-fis.csv"))
df.head()

,Nome,Razão Social,Codigo,Setor,Segmento
0,AF INVEST CRI FDO. INV. IMOB - RECEBÍVEIS IMOB.,FII AFHI CRI,AFHI,Fundo de Papel,Papéis
1,AJ MALLS FDO DE INV IMOB,FII AJ MALLS,AJFI,Fundo de Tijolo,Shoppings
2,ALIANZA CRÉDITO IMOBILIÁRIO FUNDO DE INVESTIM...,FII ALIANZAC,ALZC,Fundo de Papel,Papéis
3,ALIANZA MULTIESTRATÉGIA FUNDO DE INVESTIMENTO ...,FII ALIANZME,ALZM,Fundo de Papel,Fundo de Fundos
4,ALIANZA MULTIOFFICES - FDO. INV. IMOB,FII MULT OF1,MTOF,Fundo de Tijolo,Lajes Corporativas

In [33]:
# Define a reusable function for running SQL queries
run_query = lambda query: sqldf(query, globals())

## Conhecendo os dados

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 465 entries, 0 to 464
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Nome          465 non-null    str
 1   Razão Social  465 non-null    str
 2   Codigo        465 non-null    str
 3   Setor         465 non-null    str
 4   Segmento      465 non-null    str
dtypes: str(5)
memory usage: 18.3 KB

In [23]:
df.describe()

,Nome,Razão Social,Codigo,Setor,Segmento
count,465,465,465,465,465
unique,440,440,440,3,15
top,BANRISUL NOVAS FRONTEIRAS FDO INV IMOB - FII,FII BANRISUL,BNFS,Fundo de Tijolo,Papéis
freq,7,7,7,198,86

In [24]:
df.head()

,Nome,Razão Social,Codigo,Setor,Segmento
0,AF INVEST CRI FDO. INV. IMOB - RECEBÍVEIS IMOB.,FII AFHI CRI,AFHI,Fundo de Papel,Papéis
1,AJ MALLS FDO DE INV IMOB,FII AJ MALLS,AJFI,Fundo de Tijolo,Shoppings
2,ALIANZA CRÉDITO IMOBILIÁRIO FUNDO DE INVESTIM...,FII ALIANZAC,ALZC,Fundo de Papel,Papéis
3,ALIANZA MULTIESTRATÉGIA FUNDO DE INVESTIMENTO ...,FII ALIANZME,ALZM,Fundo de Papel,Fundo de Fundos
4,ALIANZA MULTIOFFICES - FDO. INV. IMOB,FII MULT OF1,MTOF,Fundo de Tijolo,Lajes Corporativas

In [26]:
df.sample(5)

,Nome,Razão Social,Codigo,Setor,Segmento
362,RB CAPITAL RECEBÍVEIS IMOB. FDO. INVEST. IMOB FII,FII RBCAP RI,RRCI,Fundo de Papel,Papéis
307,LCP SPECIAL OPPORTUNITIES I FDO INV IMOB RESP,FII LSOI,LSOI,Fundo Misto,Misto
202,FUND. INVEST. IMOB. SUCCESPAR VAREJO,FII S VAREJO,SPVJ,Fundo de Tijolo,Shoppings
217,FUNDO DE INVESTIMENTO IMOBILIÁRIO CAIXA AGÊNCIAS,FII CAIXA AG,CXAG,Fundo de Tijolo,Agências de Bancos
446,VINCI IMÓVEIS URBANOS FDO. DE INV. IMOB.,FII VINCI IU,VIUR,Fundo Misto,Misto

In [27]:
df.tail()

,Nome,Razão Social,Codigo,Setor,Segmento
460,XP SELECTION FDO DE FUNDOS INV IMOB - FII,FII XP SELEC,XPSF,Fundo de Papel,Fundo de Fundos
461,YUCA FDO INV. IMOB.,FII YUCA,YUFI,Fundo Misto,Fundo de Desenvolvimento
462,ZAVIT CRÉDITO IMOBILIÁRIO - FDO INV IMOB,FII ZAVIT C,ZAVC,Fundo Misto,Indefinido
463,ZAVIT REAL ESTATE FUND - FDO INV IMOB,FII ZAVIT R,ZAVI,Fundo Misto,Indefinido
464,ZION CAPITAL FUNDO DE INVESTIMENTO IMOBILIÁRIO...,FII ZION,ZIFI,Fundo Misto,Fundo de Desenvolvimento

In [28]:
df.columns

Index(['Nome', 'Razão Social', 'Codigo', 'Setor', 'Segmento'], dtype='str')

## Respondendo perguntas
- Quantidade de segmentos diferentes
- Quantos tipos de segmentos disponiveis
- Quantos setores diferentes
- Quantidade de fundos por segmento
- Quais tickers estão em cada segmento

In [ ]:
# qtde segmentos 
query_qtde_segmento = """
    SELECT COUNT(DISTINCT Segmento ) as qtde_segmentos
        FROM df
"""
result_qtde_segmento = run_query(query_qtde_segmento)
print(result_qtde_segmento)

   qtde_segmentos
0              15

In [37]:
# quais os segmentos
query_seg_disp = """ 
    SELECT DISTINCT Segmento
        FROM df
"""
result_segmento_disp = run_query(query_seg_disp)
print(result_segmento_disp)

                            Segmento
0                             Papéis
1                          Shoppings
2                    Fundo de Fundos
3                 Lajes Corporativas
4                              Misto
5        Imóveis Comerciais - Outros
6               Imóveis Residenciais
7   Imóveis Industriais e Logísticos
8                 Agências de Bancos
9                         Indefinido
10          Fundo de Desenvolvimento
11                            Hotéis
12                            Varejo
13                       Educacional
14                        Hospitalar

In [ ]:
# setores diferentes
query_setor = """ 
    SELECT DISTINCT Setor
        FROM df
"""
result_setor = run_query(query_setor)
print(result_setor)

             Setor
0   Fundo de Papel
1  Fundo de Tijolo
2      Fundo Misto

In [46]:
# qtde fundos por segmento
query_qtde_fundos_segmento = """ 
    SELECT COUNT(DISTINCT Segmento) as qtde_fundos_segmento,
            Setor
        FROM df
    GROUP BY Setor
"""
result_qtde_fundos_segmento = run_query(query_qtde_fundos_segmento)
print(result_qtde_fundos_segmento)

   qtde_fundos_segmento            Setor
0                     3      Fundo Misto
1                     2   Fundo de Papel
2                    10  Fundo de Tijolo

In [56]:
# quais os tickers estao em cada segmento
query_ticker_segmento = """ 
   SELECT DISTINCT( Codigo ) as Codigo,
            Segmento    
        FROM df
    GROUP BY Segmento
    ORDER BY Segmento
"""
result_ticker_segmento = run_query(query_ticker_segmento)
print(result_ticker_segmento)

   Codigo                          Segmento
0    BNFS                Agências de Bancos
1    FAED                       Educacional
2    BRIM          Fundo de Desenvolvimento
3    ALZM                   Fundo de Fundos
4    HCRI                        Hospitalar
5    BTHI                            Hotéis
6    AURB       Imóveis Comerciais - Outros
7    AROA  Imóveis Industriais e Logísticos
8    APXR              Imóveis Residenciais
9    BRSE                        Indefinido
10   MTOF                Lajes Corporativas
11   ALZR                             Misto
12   AFHI                            Papéis
13   AJFI                         Shoppings
14   DLMT                            Varejo